name:  Dockerize Node.js application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:    
      - name: Check out de repo
        uses: actions/checkout@v3
      
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: marciofariajr/api-tp6
          tags: latest, ${{ github.run_number }}
          